[FEAT] Concert 조회, 삽입, 삭제 구현
prgrms-be-devcourse/NBE1_2_Team02 pull request #14
Opened 2024-09-24 12:07 UTC by kwanse

이후에 최적화가 필요합니당 (Create 시 쿼리 101개..)

2024-09-24 12:45 UTC, AnTaeho reviewed
고생하셨습니다! 
몇가지 궁금한 점이랑 의견 남겨봤습니다!

2024-09-24 12:45 UTC, AnTaeho commented on src/main/java/com/example/book_your_seat/concert/controller/dto/AddConcertRequest.java
> +) {
Validation을 통과하지 못했을 때의 메세지도 추가해주시면 좋을 것 같습니다!

2024-09-24 12:45 UTC, AnTaeho commented on src/main/java/com/example/book_your_seat/concert/controller/dto/ConcertResponse.java
> +    }
static 메서드로 사용하는게 가독성이 좋을거 같네요! 
저도 앞으로 이렇게 작성해보겠습니다!

2024-09-24 12:45 UTC, AnTaeho commented on src/main/java/com/example/book_your_seat/concert/domain/Concert.java
> +    private Integer totalStock;
잘 몰라서 그런데 int 일 때와 Integer 일 때의 차이점이 무엇인가요?

2024-09-24 12:45 UTC, AnTaeho commented on src/main/java/com/example/book_your_seat/concert/domain/Concert.java
>      }
아마도 Create 할 때 쿼리 101개가 공연 1개에 좌석 100개 같은데 
좌석을 생성하는 부분을 JPA 의 Dirty Checking으로 하는 것보다 jdbcTemplate 사용해서 
bulk Insert로 구현하면 쿼리 2개로 해결할 수 있을 것 같습니다! 

JPA에서는 saveAll() 메서드를 사용해도 bulk Insert를 해주지 않아서 
이런 경우에  jdbcTemplate 사용해서 구현할 수 있습니다! 

https://velog.io/@joonghyun/Spring-JPA-Save-vs-SaveAll-vs-Bulk-Insert

별개로 삽입의 경우엔 상관 없는데, 벌크로 업데이트를 하면 
영속성 컨텍스트에 반영되지 않기때문에 정합성을 주의해주어야 하긴 합니다!

2024-09-24 12:45 UTC, AnTaeho commented on src/main/java/com/example/book_your_seat/concert/repository/ConcertRepository.java
> +@Repository
제가 알기로 JPARepository를 상속 받으면 @Repository가 필요 없는 것으로 알고 있는데
리포지토리라는 것을 명시해주기 위해서 작성하신건가요?
그렇다면 저는 있어도 좋다고 생각합니다!

2024-09-24 12:50 UTC, kwanse commented on src/main/java/com/example/book_your_seat/concert/domain/Concert.java
> +    private Integer totalStock;
> 잘 몰라서 그런데 int 일 때와 Integer 일 때의 차이점이 무엇인가요?

int 로 설정하였을 때 totalStock 이 0 인 경우 문제가 생길 수 있습니당 null 이라는 의미인지 0이라는 의미인지 구분하기 힘들기 때문에 Integer 로 줬습니당 Id 값으로 long 이 아닌 Long 을 주는 것도 같은 이유입니당

2024-09-24 12:51 UTC, kwanse commented on src/main/java/com/example/book_your_seat/concert/domain/Concert.java
>      }
> 아마도 Create 할 때 쿼리 101개가 공연 1개에 좌석 100개 같은데 좌석을 생성하는 부분을 JPA 의 Dirty Checking으로 하는 것보다 jdbcTemplate 사용해서 bulk Insert로 구현하면 쿼리 2개로 해결할 수 있을 것 같습니다!
> 
> JPA에서는 saveAll() 메서드를 사용해도 bulk Insert를 해주지 않아서 이런 경우에 jdbcTemplate 사용해서 구현할 수 있습니다!
> 
> https://velog.io/@joonghyun/Spring-JPA-Save-vs-SaveAll-vs-Bulk-Insert
> 
> 별개로 삽입의 경우엔 상관 없는데, 벌크로 업데이트를 하면 영속성 컨텍스트에 반영되지 않기때문에 정합성을 주의해주어야 하긴 합니다!

내일은 bulk insert 한번 해보겠읍니다 참고자료까지 꿀과 젖이 넘쳐 흐르는군요... 감사합니당

2024-09-24 12:51 UTC, kwanse commented on src/main/java/com/example/book_your_seat/concert/repository/ConcertRepository.java
> +@Repository
> 제가 알기로 JPARepository를 상속 받으면 @repository가 필요 없는 것으로 알고 있는데 리포지토리라는 것을 명시해주기 위해서 작성하신건가요? 그렇다면 저는 있어도 좋다고 생각합니다!

그냥 이름표 같은 느낌으로 줘봤습니당..!

2024-09-24 12:52 UTC, kwanse commented on src/main/java/com/example/book_your_seat/concert/controller/dto/AddConcertRequest.java
> +) {
> **P2** Validation을 통과하지 못했을 때의 메세지도 추가해주시면 좋을 것 같습니다!

헉 맞네요 감사합니다 ㅜㅜ

2024-09-24 12:53 UTC, kwanse commented on src/main/java/com/example/book_your_seat/concert/controller/dto/ConcertResponse.java
> +    }
> static 메서드로 사용하는게 가독성이 좋을거 같네요! 저도 앞으로 이렇게 작성해보겠습니다!

TMI 이긴 하지만 record 로 해버리면 정적팩토리 메소드 '만' 사용해서 생성하는 것이 불가능 하기 때문에 class 로 해줬습니다 하하

2024-09-24 12:55 UTC, kcsc2217 commented on src/main/java/com/example/book_your_seat/concert/controller/dto/AddConcertRequest.java
> +                return new Concert(request.title, TOTAL_STOCK,
P5: 단지 궁금한건데 record를 사용하면 getter와 setter 를 내장하고 있는건가요??

2024-09-24 12:58 UTC, kwanse commented on src/main/java/com/example/book_your_seat/concert/controller/dto/AddConcertRequest.java
> +                return new Concert(request.title, TOTAL_STOCK,
> P5: 단지 궁금한건데 record를 사용하면 getter와 setter 를 내장하고 있는건가요??

record 를 사용하면 @RequiredArgsConstructor + @Getter 라고 보시면 됩니당 @Setter 는 없습니당 record 는 클래스와 모든 필드가 final 로 선언되기 때문에 생성하는 순간에 값을 전달해주어야 합니당 그리고 @Getter 도 user.getId() 의 형식이 아닌 user.id 로 꺼내버릴수있습니당

2024-09-24 13:00 UTC, AnTaeho commented on src/main/java/com/example/book_your_seat/concert/controller/dto/ConcertResponse.java
> +    }
가독성을 위해서 record를 포기하는 걸로.... 
나중에 코틀린 가면 다시 이쁘게 만들 수 있을겁니다

2024-09-24 13:03 UTC, tnals2384 commented on src/main/java/com/example/book_your_seat/concert/domain/Concert.java
P1 
예매시작시간도 추가해야 할 것 같습니다!! 예매 시작 시간에 티켓팅을 시작해서 그 전에는 예매가 안되게 해야할 것 같아요!!

2024-09-24 13:08 UTC, tnals2384 requested changes

2024-09-24 13:08 UTC, tnals2384 commented on src/main/java/com/example/book_your_seat/concert/domain/Concert.java
P1 
예매시작시간도 추가해야 할 것 같습니다!! 예매 시작 시간에 티켓팅을 시작해서 그 전에는 예매가 안되게 해야할 것 같아요!!

2024-09-24 13:08 UTC, tnals2384 commented on src/main/java/com/example/book_your_seat/concert/service/ConcertCommandServiceImpl.java
> +        concertRepository.deleteById(id);
P4 
delete 시 유효 id 검증은 따로 하지 않는지 궁금합니당~!!

2024-09-24 13:11 UTC, AnTaeho commented on src/main/java/com/example/book_your_seat/concert/service/ConcertCommandServiceImpl.java
> +        concertRepository.deleteById(id);
만약 ID 가 존재하는지 검증이라면 deleteById를 하면 내부적으로 findById를 한번 하는 걸로 알고 있습니다! 

https://hwanchang.tistory.com/7

2024-09-24 13:15 UTC, tnals2384 commented on src/main/java/com/example/book_your_seat/concert/service/ConcertCommandServiceImpl.java
> +        concertRepository.deleteById(id);
굳이 findById로 쿼리한 번 더 날려서 예외처리 따로해주는거보다 그냥 내부적으로 리턴되는 예외를 그대로 리턴하는 느낌일까요??!

2024-09-24 13:18 UTC, kcsc2217 commented on src/main/java/com/example/book_your_seat/concert/controller/dto/AddConcertRequest.java
> +                return new Concert(request.title, TOTAL_STOCK,
바인딩 할때 프로퍼티 접근법을 사용하는걸로 알고 있는데 setter가 없으면 final 로 선언되어 생성 시점에 주입을 해주는걸까요!! 제가 이해한게 맞을까요!

2024-09-24 13:27 UTC, kcsc2217 commented on src/main/java/com/example/book_your_seat/concert/service/ConcertCommandServiceImpl.java
> +        concertRepository.deleteById(id);
연관관계가 묶여 있으면 곧 바로 deleteById를 해주면 안되고 findById를 먼저 한 후에 연관관계를 제거하고 delete를 해주는게 맞을까요??? 어디서 본 거 같은데 확실치가 않아서요..

2024-09-24 13:32 UTC, AnTaeho commented on src/main/java/com/example/book_your_seat/concert/service/ConcertCommandServiceImpl.java
> +        concertRepository.deleteById(id);
네네 근데 좀 더 찾아보니까 직접 예외 처리 해주고 싶다면 findById랑 delete 사용하는게 더 좋을거 같기도 하네요!

2024-09-24 14:36 UTC, kimdw0823 commented on src/test/java/com/example/book_your_seat/service/ConcertServiceTest.java
> +class ConcertServiceTest extends IntegerTestSupport {
이렇게 따로 IntegerTestSupport 클래스를 만들고 상속 받아서 쓰는 장점이 궁금합니다....!!!

2024-09-25 04:55 UTC, tnals2384 approved these changes

2024-09-25 04:58 UTC, AnTaeho approved these changes
고생하셨습니다!

2024-09-25 05:05 UTC, kimdw0823 approved these changes
고생하셨어요

2024-09-25 05:20 UTC, AnTaeho approved these changes
좋습니다

2024-09-25 05:24 UTC, merged